<?php

namespace ImieBundle\Repository;

/**
 * vehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vehiculeRepository extends \Doctrine\ORM\EntityRepository
{
}
